using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ScentAir.Payment.Models
{

    public class SFContact : Impl.AuditableEntity
    {
        //ContactFullId                                     // SalesForce unique identifier for the Account record, used in Richa's sync process; 
                                                            //   we don't need to update or even read this value in the Portal app.
        //Id                   id                           // Identity value auto-generated by the database; we don't need to add or update this.
        //AccountNumber        accountNumber
        //FirstName	           firstName	
        //LastName             lastName
        //Email                email
        //Phone                phone
        //MainContact          mainContact
        //BillingContact       billingContact
        //ShippingContact      shippingContact
        //ServiceContact       serviceContact
        //PropertyContact      propertyContact
        //InstallationContact  installationContact
        //MarketingContact     marketingContact
        //DoNotCall	           doNotCall	
        //DoNotEmail           doNotEmail
        //Active               active

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [StringLength(15)]                                  // SalesForce column length is 1300, but this must match Accounts table column length of 15 for foreign key.
        public string AccountNumber { get; set; }

        [StringLength(40)]                                  // SalesForce column length is 40. SF allows NULLs.
        public string FirstName { get; set; }
        [Required]
        [StringLength(80)]                                  // SalesForce column length is 80.
        public string LastName { get; set; }
        [StringLength(80)]                                  // Standard Email column length is 100, but the SalesForce column length is 80.
        public string Email { get; set; }
        [StringLength(40)]                                  // Standard Phone column length is 84, but the SalesForce column length is 40.
        public string Phone { get; set; }
        public bool MainContact { get; set; }
        public bool BillingContact { get; set; }
        public bool ShippingContact { get; set; }
        public bool ServiceContact { get; set; }
        public bool PropertyContact { get; set; }
        public bool InstallationContact { get; set; }
        public bool MarketingContact { get; set; }
        public bool DoNotCall { get; set; }
        public bool DoNotEmail { get; set; }
        public bool Active { get; set; }
    }
}
